"""Initial migration.

Revision ID: 173ae13ab5da
Revises: 
Create Date: 2024-07-06 21:23:18.669449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '173ae13ab5da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.drop_column('purchased')

    # ### end Alembic commands ###
