"""Migracion002

Revision ID: e1953bb836a2
Revises: 3deda34f42ff
Create Date: 2024-07-05 19:10:26.298439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1953bb836a2'
down_revision = '3deda34f42ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clase',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=80), nullable=True),
    sa.Column('horas', sa.Float(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('THours', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.drop_column('THours')

    op.drop_table('clase')
    # ### end Alembic commands ###
